// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDiJFbeOFBo7YQoeY0ha9qa4Nn8_nDER4',
    appId: '1:128663208752:web:4e8df906249f3c74b03ef5',
    messagingSenderId: '128663208752',
    projectId: 'eduflow-6ed1f',
    authDomain: 'eduflow-6ed1f.firebaseapp.com',
    storageBucket: 'eduflow-6ed1f.firebasestorage.app',
    measurementId: 'G-7P3BJ3Z7FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJXZoEvk5qBXGkwimE_ti_6UnCS17eqx8',
    appId: '1:128663208752:android:5a10a05c2b69b1e3b03ef5',
    messagingSenderId: '128663208752',
    projectId: 'eduflow-6ed1f',
    storageBucket: 'eduflow-6ed1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4BRjVUwBWqzmclr8HNs8pIrn9N_8LC7A',
    appId: '1:128663208752:ios:342bedc7ba04c0beb03ef5',
    messagingSenderId: '128663208752',
    projectId: 'eduflow-6ed1f',
    storageBucket: 'eduflow-6ed1f.firebasestorage.app',
    iosBundleId: 'com.eduflow.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4BRjVUwBWqzmclr8HNs8pIrn9N_8LC7A',
    appId: '1:128663208752:ios:177e735e7f3d6829b03ef5',
    messagingSenderId: '128663208752',
    projectId: 'eduflow-6ed1f',
    storageBucket: 'eduflow-6ed1f.firebasestorage.app',
    iosBundleId: 'com.example.smartStudyPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDiJFbeOFBo7YQoeY0ha9qa4Nn8_nDER4',
    appId: '1:128663208752:web:d4add523599a26f1b03ef5',
    messagingSenderId: '128663208752',
    projectId: 'eduflow-6ed1f',
    authDomain: 'eduflow-6ed1f.firebaseapp.com',
    storageBucket: 'eduflow-6ed1f.firebasestorage.app',
    measurementId: 'G-TX3E40JFC0',
  );

}